services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ADMIN1
      - POSTGRES_PASSWORD=ADMIN1
      - POSTGRES_DB=xyz_labs_dev
  celery:
     build: ./app
     command: celery --app=XYZ_labs worker --loglevel=info --logfile=logs/celery.log
     volumes:
      - ./app/:/usr/src/app/
     environment:
       - DEBUG=1
       - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
       - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
       - CELERY_BROKER=redis://redis:6379/0
       - CELERY_BACKEND=redis://redis:6379/0
     depends_on:
       - web
       - redis
  dashboard:
    build: ./project
    command: celery -A core --broker=redis://redis:6379/0 flower --port=5555 
    ports:
      - 5555:5555
    environment:
    - DEBUG=1
    - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
    - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    - CELERY_BROKER=redis://redis:6379/0
    - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - celery
  redis:
    image: redis:5-alpine
volumes:
  postgres_data: